apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfile | quote }}
  LOGGING_LEVEL_ROOT: {{ .Values.config.loggingLevel | quote }}
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
