apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
type: Opaque
data:
  DB_HOST: {{ .Values.secret.dbHost | b64enc }}
  DB_PORT: {{ .Values.secret.dbPort | b64enc }}
  DB_NAME: {{ .Values.secret.dbName | b64enc }}
  DB_USERNAME: {{ .Values.secret.dbUsername | b64enc }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword | b64enc }}
