apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
  namespace: myapp
  labels:
    app: myapp
    version: "0.0.1"
    component: secret
    managed-by: kubectl
type: Opaque
data:
  DB_HOST: cG9zdGdyZXM=
  DB_PORT: NTQzMg==
  DB_NAME: bXlhcHA=
  DB_USERNAME: bXlhcHA=
  DB_PASSWORD: Y2hhbmdlbWU=
  POSTGRES_PASSWORD: Y2hhbmdlbWU=
