apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: myapp
  labels:
    app: myapp
    version: "0.0.1"
    component: service
    managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
