apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp
  namespace: myapp
  labels:
    app: myapp
    version: "0.0.1"
    component: serviceaccount
    managed-by: kubectl
automountServiceAccountToken: false
