---
- name: Build Docker image
  command: docker build -t awsattemptacr.azurecr.io/aws-attempt:{{ image_tag }} .
  args:
    chdir: "{{ project_root }}"

- name: Login to ACR
  command: az acr login --name awsattemptacr

- name: Push image to ACR
  command: docker push awsattemptacr.azurecr.io/aws-attempt:{{ image_tag }}

- name: Update Container App to new image
  command: >
    az containerapp update
    --name aws-attempt-app
    --resource-group aws-attempt-rg
    --image awsattemptacr.azurecr.io/aws-attempt:{{ image_tag }}